project_id = "oaabtbvwxsjomeeizciq"

[functions.mqtt-collector]
verify_jwt = false

[functions.mqtt-ping]
verify_jwt = false

[functions.relay-control]
verify_jwt = false

[functions.export-readings]
verify_jwt = false

[functions.ai-analytics]
verify_jwt = false

[functions.ai-analytics-enhanced]
verify_jwt = false

[functions.process-knowledge]
verify_jwt = false

[functions.knowledge-search]
verify_jwt = false